apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
type: Opaque
stringData:
  # Internal DB credentials
  POSTGRES_USER: todo_user
  POSTGRES_PASSWORD: todo_password
  POSTGRES_DB: todo_db
  
  # JWT Secret
  JWT_SECRET_KEY: "super-secret-key-change-in-production"
