apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-backend
  labels:
    app: {{ include "todo-app.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "todo-app.fullname" . }}-backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.service.port }}
        envFrom:
        - configMapRef:
            name: {{ include "todo-app.fullname" . }}-config
        - secretRef:
            name: {{ include "todo-app.fullname" . }}-secrets
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
