apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
data:
  # Python/Backend
  DATABASE_URL: "postgresql://{{ .Values.postgres.credentials.user }}:{{ .Values.postgres.credentials.password }}@{{ include "todo-app.fullname" . }}-postgres:5432/{{ .Values.postgres.credentials.db }}"
  PORT: "{{ .Values.backend.service.port }}"
  
  # Node/Frontend
  NODE_ENV: "{{ .Values.global.environment }}"
  BACKEND_URL: "http://{{ include "todo-app.fullname" . }}-backend:{{ .Values.backend.service.port }}"
  NEXT_PUBLIC_API_BASE_URL: "http://localhost:{{ .Values.backend.service.port }}" # Placeholder - update after deployment
