apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    app: {{ include "todo-app.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ include "todo-app.fullname" . }}-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 3000
    nodePort: {{ .Values.frontend.service.nodePort }}
    protocol: TCP
