apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.fullname" . }}-secrets
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.credentials.db | quote }}
  JWT_SECRET_KEY: {{ .Values.jwt.secret | quote }}
